version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  aws-ecr: circleci/aws-ecr@0.0.4

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build app
          command: npm install
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  
  deploy: 
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true 

workflows:
  test_my_app:
    jobs:
      - build_and_test      
      - aws-ecr/build_and_push_image:
          region: ${AWS_REGION}
          account-url: ${AWS_ECR_ACCOUNT_URL}
          repo: ${AWS_RESOURCE_NAME_PREFIX}
          tag: ${CIRCLE_BUILD_NUM}
          requires:
            - build_test
      - deploy:
          requires:
            - build_and_test 
          filters:
            branches:
              only: main 
